name: meu_orcamento
description: Meu Orçamento é um aplicativo de gestão financeira que permite ao usuário controlar seus gastos de forma simples e eficiente. Com um valor inicial definido pelo usuário, é possível adicionar despesas com seus respectivos nomes e valores, e acompanhar em tempo real o saldo restante disponível. Com uma interface intuitiva o Meu Orçamento ajuda o usuário a ter um maior controle sobre suas finanças e a tomar decisões mais conscientes em relação aos seus gastos.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-118.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  hive_flutter: ^1.1.0
  open_file: ^3.3.2
  syncfusion_flutter_charts: ^21.2.10
  syncfusion_flutter_pdf: ^21.2.10

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/app/splash-image.png"
  android: true

flutter_icons:
  image_path: "assets/app/icone-image.png"
  android: "launcher_icon"
  adaptative_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app/transparent-icone-image.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
