name: orcamento_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-233.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  open_file: ^3.2.1
  path_provider: ^2.0.14 
  syncfusion_flutter_charts: ^21.1.41
  syncfusion_flutter_pdf: ^21.1.38

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.5

flutter:
  uses-material-design: true
  assets:
    - images/