name: meu_orcamento
description: Meu Orçamento é um aplicativo de gestão financeira que permite ao usuário controlar seus gastos de forma simples e eficiente. Com um valor inicial definido pelo usuário, é possível adicionar despesas com seus respectivos nomes e valores, e acompanhar em tempo real o saldo restante disponível. Com uma interface intuitiva o Meu Orçamento ajuda o usuário a ter um maior controle sobre suas finanças e a tomar decisões mais conscientes em relação aos seus gastos.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-118.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  open_file: ^3.3.2
  syncfusion_flutter_charts: ^21.2.10
  syncfusion_flutter_pdf: ^21.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
